# Generated by Django 5.2.6 on 2025-09-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enrolled_courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="lms_app.course"
            ),
        ),
    ]
